version: "3.9"
services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - spring
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 768M
        reservations:
          memory: 512M
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411"
    networks:
      - spring

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - spring
  broker:
    image: confluentinc/cp-kafka:latest
    container_name: broker
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    networks:
      - spring
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config-server/prometheus.yml:/etc/config-server/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/config-server/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    networks:
      - spring
    restart: always
  grafana:
    image: grafana/grafana
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    links:
      - prometheus:prometheus
    depends_on:
      - prometheus
    ports:
      - "3000:3000"
    networks:
      - spring
    restart: always
  eureka-server:
    build: ./eureka-server
    image: fups/eureka-server:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
  kafka:
    build: ./kafka
    image: fups/kafka:latest
    container_name: kafka
    ports:
      - "9999:9999"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SPRING_KAFKA_BOOTSTRAPSERVERS=broker:29092
    depends_on:
      - broker
    networks:
      - spring
  user:
    build: ./user
    image: fups/user:latest
    container_name: user
    ports:
      - "8181:8181"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/fups_user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - postgres
    networks:
      - spring
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
  user_2:
    build: ./user
    image: fups/user:latest
    container_name: user_2
    ports:
      - "8182:8182"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/fups_user
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
      - SERVER_PORT=8182
    depends_on:
      - postgres
    networks:
      - spring
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
  order:
    build: ./order
    image: fups/order:latest
    container_name: order
    ports:
      - "8281:8281"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/fups_order
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    depends_on:
      - postgres
    networks:
      - spring
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
  saga-orchestration:
    build: ./saga-orchestration
    image: fups/saga-orchestration:latest
    container_name: saga-orchestration
    ports:
      - "5454:5454"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring
    depends_on:
      - user
      - order
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
  api-gateway:
    build: ./api-gateway
    image: fups/api-gateway:latest
    container_name: api-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka
    networks:
      - spring
    depends_on:
      - user
      - saga-orchestration
    deploy:
      resources:
        limits:
          memory: 1024M
        reservations:
          memory: 768M
networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge
volumes:
  postgres: