spring:
  application:
    name: api-gateway
  mvc:
    problem-details:
      enabled: true
  profiles:
    active:
      - dev

  cloud:
    loadbalancer:
      ribbon:
        enable: true

spring-doc:
  swagger-ui:
    path: /swagger-ui.html

server:
  port: 8080
  error:
    include-message: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
  instance:
    preferIpAddress: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0